'use strict';

module.exports = {
    'main-theme-color': '#4899FF',
    'main-theme-dark': '#4C6682',
    'main-theme-light': 'rgba(24, 162, 255, .9)',
    'main-theme-lightest': 'rgba(24, 162, 255, .1)',
    white: '#fff',
    whiteFilter: 'rgba(256, 256, 256, .3)',
    red: '#FF6865',
    redDark: '#FF4F54',
    redLight: '#FF7148',
    orange: '#f08d49',
    yellow: '#FFF5C9',
    'text-color': '#333',
    'text-color-normal': '#666',
    'text-color-light': '#999',
    'text-color-lighter': '#b2b2b2',
    'text-color-grayBlue': '#4B627F',
    'text-color-dark': '#151515',
    'text-color-gray': '#bbb',
    'border-color': '#e1e2e3',
    'border-color-dark': '#e5e5e5',
    'border-color-light': '#f0f0f0',
    'border-color-darker': '#dbdbdb',
    'border-color-darkest': '#d5d5d5',
    'background-color': 'rgba(232, 232, 232, .5)',
    'background-blue-dark': '#d3dfed',
    'background-gray-color': '#fbfbfb',
    'background-grayer-color': '#f3f5f9',
    'background-grayest-color': '#ebebeb',
    'background-grayLight-color': '#f4f4f4',
};
